In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset= pd.read_csv('Data.csv')

#seprate matrix and vector of dependent and independent variable from dataframe

#YOU CAN USE Shift+Enter KEY TO SEE ANY FUNCTION ARGUMENT

# Single selections using iloc and DataFrame
# Rows:
data.iloc[0] # first row of data frame (Aleshia Tomkiewicz) - Note a Series data type output.
data.iloc[1] # second row of data frame (Evan Zigomalas)
data.iloc[-1] # last row of data frame (Mi Richan)
# Columns:
data.iloc[:,0] # first column of data frame (first_name)
data.iloc[:,1] # second column of data frame (last_name)
data.iloc[:,-1] # last column of data frame (id)

# Multiple row and column selections using iloc and DataFrame
data.iloc[0:5] # first five rows of dataframe
data.iloc[:, 0:2] # first two columns of data frame with all rows
data.iloc[[0,3,6,24], [0,5,6]] # 1st, 4th, 7th, 25th row + 1st 6th 7th columns.
data.iloc[0:5, 5:8] # first 5 rows and 5th, 6th, 7th columns of data frame (county -> phone1).

#dataset.iloc[rows,colums]  
#note [2:6] means from 3rd to 6th row/colum

In [13]:
#choose X= all rows & last column
X = dataset.iloc[ : , :-1].values

#choose Y= all rows & 4th column
Y = dataset.iloc[ : , 3].values

In [14]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [16]:
#to handle & implement missing bank values  

from sklearn.preprocessing import Imputer


missing_values:

Define your missing value. In python, if you double click and visualize your data, then you will see the blank data = ‘NaN. So in this case, we are going to set missing_values=’NaN’

strategy:

You can replace the missing data with  the following values
1.) Mean
2.) Median
3.) Most_frequent i.e.(Mode) 

axis:

1.) axis =0  This means that the computer will take the mean per column

2.) axis =1  This means that the computer will take the mean per row

In [27]:
Imputer=Imputer(missing_values='NaN', strategy='mean', axis=0)

In [38]:
#Apply imputer to your data


Imputer = Imputer.fit(X[ : , 1:3])

#Replace your blank observations with the calcuated value.

X[ : , 1:3] = Imputer.transform(X[ : , 1:3])

In [44]:
# look NaN is gone
X[ : , 1:3]


array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, 63777.77777777778],
       [35.0, 58000.0],
       [38.77777777777778, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

In [45]:
# now encode categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])

In [56]:
X[ : ,0]

array([ 0.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.])

Original Data
–

[‘b’, 2]

–[‘c’, 3]

–[‘a’, 8]

–[‘b’, 4]

–[‘a’, 4.9]

–[‘a’, 4]

–[‘b’, 8]

–[‘c’, 8]

–[‘d’, 3]

–[‘a’, 3]

–[‘c’, 6]

Applied LabelEncoder
–

 [1, 2]

–[2, 3]

–[0, 8]

–[1, 4]

–[0, 4.9]

–[0, 4]

–[1, 8]

–[2, 8]

–[3, 3]

–[0, 3]

–[2, 6]

Applied OneHotEncoder
 [a,b,c,d, value]

[0, 1, 0, 0, 2]

[0, 0, 1, 0, 3]

[1, 0, 0, 0, 8]

[0, 1, 0, 0, 4]

[1, 0, 0, 0, 4.9]

[1, 0, 0, 0, 4]

[0, 1, 0, 0, 8]

[0, 0, 1, 0, 8]

[0, 0, 0, 1, 3]

[1, 0, 0, 0, 3]

[0, 0, 1, 0, 6]

Removed Dummy Trap
 [b,c,d, value]

[1, 0, 0, 2]

[0, 1, 0, 3]

[0, 0, 0, 8]

[1, 0, 0, 4]

[0, 0, 0, 4.9]

[0, 0, 0, 4]

[1, 0, 0, 8]

[0, 1, 0, 8]

[0, 0, 1, 3]

[0, 0, 0, 3]

[0, 1, 0, 6]

 

In [57]:
#Creating a dummy variable

onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)

In [58]:
X

array([[  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   4.40000000e+01,
          7.20000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   2.70000000e+01,
          4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   3.00000000e+01,
          5.40000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   3.80000000e+01,
          6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   4.00000000e+01,
          6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   3.50000000e+01,
          5.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00

In [61]:
from sklearn.cross_validation import train_test_split

In [63]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.33, random_state=42)

In [66]:
#calculate howmuch standard deviation each data vary

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

In [67]:
X_train

array([[ 1.41421356, -1.41421356,  1.41421356, -0.70710678, -0.70710678,
         1.77492515,  1.81473962],
       [-0.70710678,  0.70710678, -0.70710678,  1.41421356, -0.70710678,
        -1.63461486, -0.98514436],
       [ 1.41421356, -1.41421356,  1.41421356, -0.70710678, -0.70710678,
        -0.30868263,  0.47079531],
       [-0.70710678,  0.70710678, -0.70710678,  1.41421356, -0.70710678,
         0.25957403,  0.10992137],
       [-0.70710678,  0.70710678, -0.70710678, -0.70710678,  1.41421356,
        -0.11926375, -0.20117685],
       [-0.70710678,  0.70710678, -0.70710678, -0.70710678,  1.41421356,
         0.02806206, -1.20913508]])